apiServer:
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: http
insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http
database:
  host: localhost
  port: 8090
  name: balmatchum
  user: postgres
maxRequestSize: 524288
sessionLogs:
  persistentEnabled: true
  consoleEnabled: true
